package oauth2.security;

import com.nimbusds.jose.jwk.JWKSet;
import com.nimbusds.jose.jwk.RSAKey;
import com.nimbusds.jose.jwk.source.JWKSource;
import com.nimbusds.jose.proc.SecurityContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.util.UUID;

@Configuration
public class OAuth2KeyPairGenerator {

    /**
     * <p>This method is the first piece to generate the private and public keys.</p>
     *
     * <p>It just returns the key pair generated by the RSA algorithm (standard algorithm do create keys)</p>
     *
     * <p>The way this method is creating the keys is only for tests or learnings, because when the application restarts, the keys
     * is generated again, invalidating all the tokens generated by the oldest keys</p>
     *
     * <p>To avoid it, is created a file to store the keys (called keystore, and in real app in production, this file didn't even stay in the project directory)</p>
     *
     * @return KeyPair (the keys pair of: private key and public key
     * @throws IllegalStateException
     */
    @Bean
    public KeyPair generateRsaKey () {
        KeyPair keyPair;

        try {
            KeyPairGenerator generator = KeyPairGenerator.getInstance("RSA");
            generator.initialize(2048);
            keyPair = generator.generateKeyPair();
        } catch (Exception e) {
            throw new IllegalStateException(e);
        }
        return keyPair;
    }

    /**
     * <p>This method is the second gear to generate the JWK (JSON Web Key), and to create this method, we need an RSAKey object.</p>
     *
     * <p>The RSAKey method gets the key pair from the first method and turns it into an RSAKey object that holds the key pair,
     * key id and else.</p>
     *
     * @param keyPair (KeyPair object)
     * @return RSAKey object
     */

    @Bean
    public RSAKey rsaKey (KeyPair keyPair) {
        RSAPublicKey publicKey = (RSAPublicKey) keyPair.getPublic();
        RSAPrivateKey privateKey = (RSAPrivateKey) keyPair.getPrivate();

        return new RSAKey.Builder(publicKey)
                .privateKey(privateKey)
                .keyID(UUID.randomUUID().toString())
                .build();
    }

    /**
     * <p>The last gear to generate the JWK object, this method creates an JWK source by the way (a repository of JWK objects)</p>
     *
     * <p>The method creates an JWKSet object, that just set the RSAKey object into itself</p>
     *
     * @param rsaKey (RSAKey object)
     * @return JWKSource object
     */
    @Bean
    public JWKSource<SecurityContext> jwkSource (RSAKey rsaKey) {
        JWKSet jwkSet = new JWKSet(rsaKey);

        return ((jwkSelector, securityContext) -> jwkSelector.select(jwkSet));
    }
}
