server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: api-route
          uri: http://api-app:8080
          predicates:
            - Path=/api/**

        - id: auth-route
          uri: http://auth-app:9000
          predicates:
            - Path=/auth/**, /oauth2/**, /login/**

logging:
  level:
    root: WARN
