spring:
  application:
    name: api-server

  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
    url: ${DEV_API_DB_URL}
    username: ${DB_USERNAME}
    password: ${API_DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
      
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migration: true
    locations: classpath:db/migration

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

  security:
    oauth2:
      resourceserver:
        jwt:
#          jwt-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI}
          jwk-set-uri: http://localhost:9000/oauth2/jwks

  messages:
    basename: api-messages
    encoding: UTF-8

logging:
  level:
    root: WARN
    org.hibernate: ERROR

server:
  port: 8080

api_created_queue: api.user.created.queue
api_updated_queue: api.user.updated.queue
api_deleted_queue: api.user.deleted.queue

auth_exchange: auth.user.exchange
api_exchange: api.user.exchange

api_user_created_key: api.user.created
api_user_updated_key: api.user.updated
api_user_deleted_key: api.user.deleted

auth_user_created_key: auth.user.created
auth_user_updated_key: auth.user.updated
auth_user_deleted_key: auth.user.deleted